export type AuthGroup = 'TABLE_MANAGE' | 'TABLE_CREATE' | 'TABLE_EDIT' | 'TABLE_VIEW' | 'COMPETITION_MANAGE' | 'COMPETITION_CREATE' | 'COMPETITION_EDIT' | 'COMPETITION_VIEW' |
    'USER_MANAGE' | 'USER_CREATE' | 'USER_EDIT' | 'USER_VIEW' | 'TOURNAMENT_MANAGE' | 'TOURNAMENT_CREATE' | 'TOURNAMENT_EDIT' | 'TOURNAMENT_VIEW' | 'TOURNAMENT_JOIN' |
    'TEAM_MANAGE' | 'TEAM_CREATE' | 'TEAM_EDIT' | 'TEAM_ADD' | 'TEAM_VIEW' | 'TEAM_CREATE' | 'PROFILE_VIEW' | 'PROFILE_EDIT' | 'MATCH_START' | 'MATCH_CHALLENGE' |
    'RANKING_VIEW' | 'MATCH_ACCEPT';
